version: "3"

services:
  website:
    container_name: andrea-website
    build:
      context: ./website
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # - HOST="127.0.0.1"
      - PORT=3000
      - SITE=localhost:3000
      - STRAPI_CLIENT_URL=http://localhost:1337
      - STRAPI_SERVER_URL=http://dashboard:1337

  dashboard:
    container_name: andrea-dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "1337:1337"
    env_file:
      - ./dashboard/.env.prod
    depends_on:
      - dashboardDB

  dashboardDB:
    container_name: andrea-dashboard-db
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - dashboard-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env

volumes:
  dashboard-data:
