FROM node:16.19.1-bullseye-slim

# for production:
# ENV NODE_ENV production

# USER node

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

# for production:
# RUN npm ci --only=production

COPY . .

CMD ["npm", "run", "dev"]